"""Toolpath and G-code generation for the BrailleRAP printer."""

from __future__ import annotations
import time
import serial

from constants import GCode
from translate import braille_to_dot_matrix

DEFAULT_FEED_RATE = 3000    # mm/min
DEFAULT_LINE_SPACING = 10.0 # mm between braille lines
PUNCH_DWELL_MS = 150        # solenoid on-time in milliseconds


def generate_gcode(
    braille_grid: list[list[str]],
    dot_spacing_mm: float = 2.5,
    cell_spacing_mm: float = 6.0,
    line_spacing_mm: float = DEFAULT_LINE_SPACING,
    margin_left_mm: float = 10.0,
    margin_top_mm: float = 10.0,
    feed_rate: int = DEFAULT_FEED_RATE,
) -> list[str]:
    """
    Generate a complete G-code job for a braille dot grid.

    Visits every active dot in reading order (line → cell → dot-row → dot-col),
    moves the head to each position in absolute coordinates, fires the solenoid,
    then returns home when done.

    Returns a list of G-code command strings (no trailing newlines).
    """
    cmds: list[str] = []
    cmds.append("; BrailleRAP — generated by B-Code")
    cmds.append("G28")              # home all axes
    cmds.append("G90")              # absolute positioning
    cmds.append(f"G1 F{feed_rate}") # set travel feed rate

    for row_idx, row in enumerate(braille_grid):
        for col_idx, char in enumerate(row):
            matrix = braille_to_dot_matrix(char)
            cell_x = margin_left_mm + col_idx * cell_spacing_mm
            cell_y = margin_top_mm + row_idx * line_spacing_mm

            for dr, dot_cols in enumerate(matrix[:3]):  # dots 1–6 only (Grade 1)
                for dc, active in enumerate(dot_cols):
                    if not active:
                        continue
                    x = cell_x + dc * dot_spacing_mm
                    y = cell_y + dr * dot_spacing_mm
                    cmds.append(f"G1 X{x:.3f} Y{y:.3f}")
                    cmds.append(GCode.PUNCH_UP.value)
                    cmds.append(f"G4 P{PUNCH_DWELL_MS}")  # dwell (ms)
                    cmds.append(GCode.PUNCH_DOWN.value)

    cmds.append("G28")  # return home after job
    cmds.append("; End of job")
    return cmds


class PrinterConnection:
    """
    Serial connection to a RepRap printer with ok-handshake flow control.

    Each G-code line is sent only after the previous 'ok' acknowledgement,
    preventing buffer overrun and keeping the host in sync with the firmware.
    """

    def __init__(self, port: str, baud: int = 250000, timeout: float = 30.0):
        self._port = port
        self._baud = baud
        self._timeout = timeout
        self._ser: serial.Serial | None = None

    def connect(self) -> None:
        self._ser = serial.Serial(self._port, self._baud, timeout=1)
        time.sleep(2)  # wait for firmware boot / reset

    def disconnect(self) -> None:
        if self._ser and self._ser.is_open:
            self._ser.close()
        self._ser = None

    def __enter__(self) -> PrinterConnection:
        self.connect()
        return self

    def __exit__(self, *_) -> None:
        self.disconnect()

    def _wait_ok(self) -> None:
        deadline = time.time() + self._timeout
        while time.time() < deadline:
            raw = self._ser.readline()
            line = raw.decode("utf-8", errors="ignore").strip()
            if line.lower() == "ok":
                return
        raise TimeoutError(f"No 'ok' from printer within {self._timeout}s")

    def send(self, gcode: str) -> None:
        """Send one G-code command and block until firmware acknowledges."""
        self._ser.write((gcode.strip() + "\n").encode())
        self._wait_ok()

    def send_job(
        self,
        gcode_lines: list[str],
        progress_cb=None,
    ) -> None:
        """
        Send a complete list of G-code commands, skipping blanks and comments.
        progress_cb(done: int, total: int) is called after each command.
        """
        cmds = [l for l in gcode_lines if l.strip() and not l.strip().startswith(";")]
        total = len(cmds)
        for i, cmd in enumerate(cmds):
            self.send(cmd)
            if progress_cb:
                progress_cb(i + 1, total)
